tasks:
  - init: composer global require laravel/installer  && mkdir dev && cd dev && composer create-project phpmyadmin/phpmyadmin && cd .. && mysqladmin -u root password 'root';
    command: cd dev/phpmyadmin && php -S localhost:8085
image:
  file: .gitpod.Dockerfile
