tasks:
  - init:  npm install -g typescript && mkdir dev && cd dev && composer create-project phpmyadmin/phpmyadmin && cd .. && mysqladmin -u root password 'gitpod';
    command: cd dev/phpmyadmin && php -S localhost:8085
image:
  file: .gitpod.Dockerfile
